# MySQL.  Version 5.0 used.
#
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: <%= ENV['DB_USER']     %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_ADDRESS']  %>
  database: <%= ENV['DB_DATABASE'] %>

development:
  <<: *default

test:
  <<: *default
  database: people_system_test

production:
  <<: *default
